# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

branches:
  only:
    - master
    - /^release\/.*$/ # release branches
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

os:
  - linux
  - osx
  - windows

julia:
  - "1.0"
  - "1"
  - nightly

notifications:
  email: false

jobs:
  allow_failures:
    # - julia: nightly
  include:
    - stage: "Documentation"
      julia: "1.3"
      os: linux
      script:
        - julia --color=yes --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                                           Pkg.instantiate()'
        - julia --color=yes --project=docs/ docs/make.jl
      after_success: skip

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
